version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
